# MongoDB
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/blackjack}

# MySQL (R2DBC)
spring.r2dbc.url=${SPRING_R2DBC_URL:r2dbc:mysql://localhost:3306/blackjack}
spring.r2dbc.username=${SPRING_R2DBC_USERNAME:root}
spring.r2dbc.password=${SPRING_R2DBC_PASSWORD:root}

spring.r2dbc.initialization-mode=always
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql